### ISSUE TITLE
[BUG]: ansible-pull does not properly check for presence of pyvenv.cfg

### ISSUE THREAD

**Issue by nis65** [projectpotos/ansible-role-potos_basics#13]
### Description of the bug

During debugging, I removed `/var/lib/mlc/ansible` on the client completely, hoping that the next run will restore it completely. Unfortunately, this did not work.

I tracked down the issue to this line:

```bash
# Create virtualenv if not exists
if [[ -z "pyvenv.cfg" ]]; then
...
```

`-z` checks if a string has zero length, use `! -s` instead to check for the non presence of the file. From the bash man page: *`-s file`: True if file exists and has a size greater than zero.*

### Steps To Reproduce

`mlc` is my short client name, might be `potos` or sth else on your instance.

1. Remove `/var/lib/mlc/ansible`
2. run `mlc-ansible-pull`
3. Result: it will fail as the venv is not rebuilt.

**Comment by fadnincx** [comment]
:+1: Can confirm `-z` is an absolute stupid test to do there, because the length of the fixed string `pyvenv.cfg` will never be 0.

IMO we should either test as said for `-s` (file exists and is not empty) or `-f` (file exists and is regular file).

**Comment by nis65** [comment]
confirmed
