### ISSUE TITLE
[BUG]: Proper protection from "unhealthy" runs

### ISSUE THREAD

**Issue by nis65** [projectpotos/ansible-role-potos_basics#39]
### Description of the bug

During operation of my potos client, I discovered the following weaknesses in the current implementation of the `-ansible-pull` script:

* If there is no network connectivity, the script starts with deleting everything in `/var/lib/potos/ansible` and cannot do anything more, as all downloads fail. This is not really a killer, i.e. as soon as network connectivity is restored, the potos magic starts working again. However, I propose the following improvement: 
   * When there is no network connectivity, the `rm`,`mkdir`, `git clone` ... (up to and including `...playbook ... prepare`) steps are skipped and the configuration is applied according to the latest state downloaded. This would at least restore the latest known settings if anyone tampered with them locally.
   
* I implemented a `sudo` command so that end users can call `-ansible-pull` whenever they wish to. This can help in a support case where the admin fixed something in `git` and the user wants to apply it immediately and not wait for the next hour/next day. It happened to me more than once that both a manually and systemd timer triggered copy of the script ran. In the best case, the 2nd one wins and does all as expected, but `-ansible-pull` is **really** not built to be executed in parallel on the same host. I propose the following improvement: 
  * The currently implemented `flock` is applied much too late, it must be moved to the very beginning (or at least before the `rm`/`mkdir`/`git clone`) sequence...
  
@fadnincx Please let me know whether these proposals sound reasonable, I might have some time implementing/testing them.

 

### Steps To Reproduce

See above.

**Comment by nis65** [comment]
I just realized that the first bullet point is actually the same as bug #28 . I'd be happy to close #28 and continue here.

**Comment by fadnincx** [comment]
This definitely sounds reasonable. The idea of the flock was, so just one Ansible process runs at the same time, 

As I currently don't really have time here, feel free to submit a PR, I'll try to review it in a timely manner.

**Comment by nis65** [comment]
Thanks @fadnincx . This was exactly what I was hoping to hear :-) on my short list now :smile:

**Comment by fadnincx** [comment]
@nis65 merged #40, so can we close this issue or do you want to implement further measures?

**Comment by nis65** [comment]
@fadnincx Although it would be nice to keep the idea to apply the ansible config even without network connectivity, this might become more complex than I hope. The implementation you merged does nothing when there is no internet connectivity (compared to the old one, that first deleted all temporary data and then did nothing because of missing connectivity) and is quite simple and good enough for the moment. I also see more urgent issues to tackle. Closing.

**Comment by nis65** [comment]
fixed by  #40
